/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\chocolate_chips.glb --types 
*/

import type * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["Cube_-_copy"]: THREE.Mesh;
    ["Cube_-_copy_1"]: THREE.Mesh;
    ["Cube_-_copy_2"]: THREE.Mesh;
    ["Cube_-_copy_3"]: THREE.Mesh;
    ["Cube_-_copy_4"]: THREE.Mesh;
    ["Cube_-_copy_5"]: THREE.Mesh;
    ["Cube_-_copy_6"]: THREE.Mesh;
    ["Cube_-_copy_7"]: THREE.Mesh;
    ["Cube_-_copy_8"]: THREE.Mesh;
    ["Cube_-_copy_9"]: THREE.Mesh;
    ["Cube_-_copy_10"]: THREE.Mesh;
    ["Cube_-_copy_11"]: THREE.Mesh;
    ["Cube_-_copy_12"]: THREE.Mesh;
    ["Cube_-_copy_13"]: THREE.Mesh;
    ["Cube_-_copy_14"]: THREE.Mesh;
    ["Cube_-_copy_15"]: THREE.Mesh;
    ["Cube_-_copy_16"]: THREE.Mesh;
    ["Cube_-_copy_17"]: THREE.Mesh;
    ["Cube_-_copy_18"]: THREE.Mesh;
    ["Cube_-_copy_19"]: THREE.Mesh;
    ["Cube_-_copy_20"]: THREE.Mesh;
    ["Cube_-_copy_21"]: THREE.Mesh;
    ["Cube_-_copy_22"]: THREE.Mesh;
    ["Cube_-_copy_23"]: THREE.Mesh;
    ["Cube_-_copy_24"]: THREE.Mesh;
    ["Cube_-_copy_25"]: THREE.Mesh;
    ["Cube_-_copy_26"]: THREE.Mesh;
    ["Cube_-_copy_27"]: THREE.Mesh;
    ["Cube_-_copy_28"]: THREE.Mesh;
    ["Cube_-_copy_29"]: THREE.Mesh;
    ["Cube_-_copy_30"]: THREE.Mesh;
    ["Cube_-_copy_31"]: THREE.Mesh;
    ["Cube_-_copy_32"]: THREE.Mesh;
    ["Cube_-_copy_33"]: THREE.Mesh;
    ["Cube_-_copy_34"]: THREE.Mesh;
    ["Cube_-_copy_35"]: THREE.Mesh;
    ["Cube_-_copy_36"]: THREE.Mesh;
    ["Cube_-_copy_37"]: THREE.Mesh;
    ["Cube_-_copy_38"]: THREE.Mesh;
    ["Cube_-_copy_39"]: THREE.Mesh;
    ["Cube_-_copy_40"]: THREE.Mesh;
    ["Cube_-_copy_41"]: THREE.Mesh;
    ["Cube_-_copy_42"]: THREE.Mesh;
    ["Cube_-_copy_43"]: THREE.Mesh;
    ["Cube_-_copy_44"]: THREE.Mesh;
    ["Cube_-_copy_45"]: THREE.Mesh;
    ["Cube_-_copy_46"]: THREE.Mesh;
    ["Cube_-_copy_47"]: THREE.Mesh;
    ["Cube_-_copy_48"]: THREE.Mesh;
    ["Cube_-_copy_49"]: THREE.Mesh;
    ["Cube_-_copy_50"]: THREE.Mesh;
    ["Cube_-_copy_51"]: THREE.Mesh;
    ["Cube_-_copy_52"]: THREE.Mesh;
    ["Cube_-_copy_53"]: THREE.Mesh;
    ["Cube_-_copy_54"]: THREE.Mesh;
    ["Cube_-_copy_55"]: THREE.Mesh;
    ["Cube_-_copy_56"]: THREE.Mesh;
    ["Cube_-_copy_57"]: THREE.Mesh;
    ["Cube_-_copy_58"]: THREE.Mesh;
    ["Cube_-_copy_59"]: THREE.Mesh;
    ["Cube_-_copy_60"]: THREE.Mesh;
    ["Cube_-_copy_61"]: THREE.Mesh;
    ["Cube_-_copy_62"]: THREE.Mesh;
    ["Cube_-_copy_63"]: THREE.Mesh;
    ["Cube_-_copy_64"]: THREE.Mesh;
    ["Cube_-_copy_65"]: THREE.Mesh;
    ["Cube_-_copy_66"]: THREE.Mesh;
    ["Cube_-_copy_67"]: THREE.Mesh;
    ["Cube_-_copy_68"]: THREE.Mesh;
    ["Cube_-_copy_69"]: THREE.Mesh;
    ["Cube_-_copy_70"]: THREE.Mesh;
    ["Cube_-_copy_71"]: THREE.Mesh;
    ["Cube_-_copy_72"]: THREE.Mesh;
    ["Cube_-_copy_73"]: THREE.Mesh;
    ["Cube_-_copy_74"]: THREE.Mesh;
    ["Cube_-_copy_75"]: THREE.Mesh;
    ["Cube_-_copy_76"]: THREE.Mesh;
    ["Cube_-_copy_77"]: THREE.Mesh;
    ["Cube_-_copy_78"]: THREE.Mesh;
    ["Cube_-_copy_79"]: THREE.Mesh;
    ["Cube_-_copy_80"]: THREE.Mesh;
    ["Cube_-_copy_81"]: THREE.Mesh;
    ["Cube_-_copy_82"]: THREE.Mesh;
    ["Cube_-_copy_83"]: THREE.Mesh;
    ["Cube_-_copy_84"]: THREE.Mesh;
    ["Cube_-_copy_85"]: THREE.Mesh;
    ["Cube_-_copy_86"]: THREE.Mesh;
    ["Cube_-_copy_87"]: THREE.Mesh;
    ["Cube_-_copy_88"]: THREE.Mesh;
    ["Cube_-_copy_89"]: THREE.Mesh;
    ["Cube_-_copy_90"]: THREE.Mesh;
    ["Cube_-_copy_91"]: THREE.Mesh;
    Cube: THREE.Mesh;
    Sphere: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
};

export function ChocolateChips(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "./assets/chocolate_chips.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Cube_-_copy_1"].geometry}
        material={materials.Material}
        position={[0.164, -0.878, 0.471]}
        rotation={[1.375, -0.995, -1.303]}
        scale={0.019}
      />
      <mesh
        geometry={nodes["Cube_-_copy_2"].geometry}
        material={materials.Material}
        position={[0.594, 0.618, 0.558]}
        rotation={[0.335, -0.473, -0.727]}
        scale={0.034}
      />
      <mesh
        geometry={nodes["Cube_-_copy_3"].geometry}
        material={materials.Material}
        position={[0.703, 0.248, -0.673]}
        rotation={[0.362, 0.27, -1.239]}
        scale={0.012}
      />
      <mesh
        geometry={nodes["Cube_-_copy_4"].geometry}
        material={materials.Material}
        position={[-0.256, 0.663, 0.72]}
        rotation={[2.984, 1.486, -1.869]}
        scale={0.022}
      />
      <mesh
        geometry={nodes["Cube_-_copy_5"].geometry}
        material={materials.Material}
        position={[-0.172, -0.881, 0.466]}
        rotation={[-0.683, 1.155, -2.831]}
        scale={0.02}
      />
      <mesh
        geometry={nodes["Cube_-_copy_6"].geometry}
        material={materials.Material}
        position={[-0.884, -0.09, -0.493]}
        rotation={[3.021, 0.148, 2.042]}
        scale={0.031}
      />
      <mesh
        geometry={nodes["Cube_-_copy_7"].geometry}
        material={materials.Material}
        position={[-0.8, -0.35, -0.514]}
        rotation={[2.135, 0.851, 1.903]}
        scale={0.021}
      />
      <mesh
        geometry={nodes["Cube_-_copy_8"].geometry}
        material={materials.Material}
        position={[-0.105, -0.465, -0.893]}
        rotation={[1.527, -0.151, 3.073]}
        scale={0.024}
      />
      <mesh
        geometry={nodes["Cube_-_copy_9"].geometry}
        material={materials.Material}
        position={[-0.72, -0.729, -0.141]}
        rotation={[0.187, -0.484, 2.55]}
        scale={0.041}
      />
      <mesh
        geometry={nodes["Cube_-_copy_10"].geometry}
        material={materials.Material}
        position={[-0.963, -0.141, 0.304]}
        rotation={[2.363, -0.12, 1.59]}
        scale={0.034}
      />
      <mesh
        geometry={nodes["Cube_-_copy_11"].geometry}
        material={materials.Material}
        position={[0.841, 0.561, 0.021]}
        rotation={[0.594, 0.383, -1.414]}
        scale={0.015}
      />
      <mesh
        geometry={nodes["Cube_-_copy_12"].geometry}
        material={materials.Material}
        position={[-0.323, 0.56, -0.776]}
        rotation={[-0.898, 0.684, 0.185]}
        scale={0.013}
      />
      <mesh
        geometry={nodes["Cube_-_copy_13"].geometry}
        material={materials.Material}
        position={[-0.371, 0.901, -0.248]}
        rotation={[0.947, -0.659, 1.098]}
        scale={0.012}
      />
      <mesh
        geometry={nodes["Cube_-_copy_14"].geometry}
        material={materials.Material}
        position={[-0.755, -0.658, -0.213]}
        rotation={[-0.088, -0.302, 2.195]}
        scale={0.038}
      />
      <mesh
        geometry={nodes["Cube_-_copy_15"].geometry}
        material={materials.Material}
        position={[-0.349, 0.533, 0.792]}
        rotation={[0.743, -0.543, 0.23]}
        scale={0.025}
      />
      <mesh
        geometry={nodes["Cube_-_copy_16"].geometry}
        material={materials.Material}
        position={[0.468, -0.892, -0.192]}
        rotation={[0.291, -1.013, -2.457]}
        scale={0.036}
      />
      <mesh
        geometry={nodes["Cube_-_copy_17"].geometry}
        material={materials.Material}
        position={[0.321, -0.155, 0.948]}
        rotation={[-1.866, 1.05, -2.906]}
        scale={0.025}
      />
      <mesh
        geometry={nodes["Cube_-_copy_18"].geometry}
        material={materials.Material}
        position={[0.991, 0.165, -0.213]}
        rotation={[-1.894, -0.58, -1.159]}
        scale={0.038}
      />
      <mesh
        geometry={nodes["Cube_-_copy_19"].geometry}
        material={materials.Material}
        position={[-0.457, 0.884, 0.19]}
        rotation={[1.961, -0.739, 1.504]}
        scale={0.021}
      />
      <mesh
        geometry={nodes["Cube_-_copy_20"].geometry}
        material={materials.Material}
        position={[0.17, -0.718, 0.712]}
        rotation={[-0.929, 0.447, 3.084]}
        scale={0.033}
      />
      <mesh
        geometry={nodes["Cube_-_copy_21"].geometry}
        material={materials.Material}
        position={[-0.35, 0.745, 0.615]}
        rotation={[-1.942, 0.991, 3.044]}
        scale={0.038}
      />
      <mesh
        geometry={nodes["Cube_-_copy_22"].geometry}
        material={materials.Material}
        position={[0.555, 0.847, 0.12]}
        rotation={[-2.738, -0.096, -2.13]}
        scale={0.025}
      />
      <mesh
        geometry={nodes["Cube_-_copy_23"].geometry}
        material={materials.Material}
        position={[0.946, 0.217, -0.348]}
        rotation={[0.661, 0.14, -1.189]}
        scale={0.042}
      />
      <mesh
        geometry={nodes["Cube_-_copy_24"].geometry}
        material={materials.Material}
        position={[-0.847, 0.558, 0.033]}
        rotation={[2.266, -0.089, 1.629]}
        scale={0.021}
      />
      <mesh
        geometry={nodes["Cube_-_copy_25"].geometry}
        material={materials.Material}
        position={[0.917, 0.389, 0.184]}
        rotation={[1.033, -0.293, -0.721]}
        scale={0.015}
      />
      <mesh
        geometry={nodes["Cube_-_copy_26"].geometry}
        material={materials.Material}
        position={[-0.523, -0.504, -0.703]}
        rotation={[-1.974, -0.568, 0.715]}
        scale={0.022}
      />
      <mesh
        geometry={nodes["Cube_-_copy_27"].geometry}
        material={materials.Material}
        position={[-0.905, 0.322, 0.359]}
        rotation={[-0.428, 0.703, 1.845]}
        scale={0.038}
      />
      <mesh
        geometry={nodes["Cube_-_copy_28"].geometry}
        material={materials.Material}
        position={[0.124, 0.998, -0.024]}
        rotation={[-3.033, -0.654, -2.604]}
        scale={0.012}
      />
      <mesh
        geometry={nodes["Cube_-_copy_29"].geometry}
        material={materials.Material}
        position={[0.347, -0.915, -0.274]}
        rotation={[-0.093, -1.128, 3.01]}
        scale={0.025}
      />
      <mesh
        geometry={nodes["Cube_-_copy_30"].geometry}
        material={materials.Material}
        position={[0.472, -0.17, 0.892]}
        rotation={[-1.549, -0.41, -3.032]}
        scale={0.037}
      />
      <mesh
        geometry={nodes["Cube_-_copy_31"].geometry}
        material={materials.Material}
        position={[0.718, 0.717, -0.038]}
        rotation={[-0.112, 0.311, -0.857]}
        scale={0.021}
      />
      <mesh
        geometry={nodes["Cube_-_copy_32"].geometry}
        material={materials.Material}
        position={[-0.323, 0.002, -0.966]}
        rotation={[1.569, -0.121, 2.537]}
        scale={0.027}
      />
      <mesh
        geometry={nodes["Cube_-_copy_33"].geometry}
        material={materials.Material}
        position={[-0.817, -0.197, 0.577]}
        rotation={[3.05, -0.381, 1.356]}
        scale={0.026}
      />
      <mesh
        geometry={nodes["Cube_-_copy_34"].geometry}
        material={materials.Material}
        position={[-0.918, -0.143, 0.425]}
        rotation={[-0.822, 0.235, 2.217]}
        scale={0.034}
      />
      <mesh
        geometry={nodes["Cube_-_copy_35"].geometry}
        material={materials.Material}
        position={[-0.928, 0.003, 0.435]}
        rotation={[0.608, 0.606, 1.022]}
        scale={0.034}
      />
      <mesh
        geometry={nodes["Cube_-_copy_36"].geometry}
        material={materials.Material}
        position={[-0.562, -0.008, -0.844]}
        rotation={[2.513, 0.695, 1.561]}
        scale={0.018}
      />
      <mesh
        geometry={nodes["Cube_-_copy_37"].geometry}
        material={materials.Material}
        position={[-0.193, 0.744, -0.685]}
        rotation={[2.87, 0.49, -2.992]}
        scale={0.041}
      />
      <mesh
        geometry={nodes["Cube_-_copy_38"].geometry}
        material={materials.Material}
        position={[0.508, 0.877, 0.112]}
        rotation={[-2.951, -0.394, -2.532]}
        scale={0.028}
      />
      <mesh
        geometry={nodes["Cube_-_copy_39"].geometry}
        material={materials.Material}
        position={[-0.826, -0.33, 0.498]}
        rotation={[-0.534, 0.027, 1.918]}
        scale={0.032}
      />
      <mesh
        geometry={nodes["Cube_-_copy_40"].geometry}
        material={materials.Material}
        position={[-0.396, 0.397, -0.862]}
        rotation={[2.388, 0.45, 2.227]}
        scale={0.037}
      />
      <mesh
        geometry={nodes["Cube_-_copy_41"].geometry}
        material={materials.Material}
        position={[0.615, 0.544, -0.596]}
        rotation={[1.527, 1.01, -1.845]}
        scale={0.021}
      />
      <mesh
        geometry={nodes["Cube_-_copy_42"].geometry}
        material={materials.Material}
        position={[-0.88, -0.518, -0.014]}
        rotation={[-2.376, -0.512, 0.993]}
        scale={0.032}
      />
      <mesh
        geometry={nodes["Cube_-_copy_43"].geometry}
        material={materials.Material}
        position={[-0.548, 0.328, -0.806]}
        rotation={[1.746, 0.255, 2.286]}
        scale={0.04}
      />
      <mesh
        geometry={nodes["Cube_-_copy_44"].geometry}
        material={materials.Material}
        position={[-0.628, 0.596, -0.559]}
        rotation={[2.634, 0.781, 2.715]}
        scale={0.043}
      />
      <mesh
        geometry={nodes["Cube_-_copy_45"].geometry}
        material={materials.Material}
        position={[-0.156, 0.996, -0.07]}
        rotation={[-2.139, 0.848, 1.957]}
        scale={0.016}
      />
      <mesh
        geometry={nodes["Cube_-_copy_46"].geometry}
        material={materials.Material}
        position={[-0.379, 0.888, -0.307]}
        rotation={[-2.297, 0.609, 2.083]}
        scale={0.023}
      />
      <mesh
        geometry={nodes["Cube_-_copy_47"].geometry}
        material={materials.Material}
        position={[-0.687, 0.6, -0.477]}
        rotation={[-0.843, 0.364, 1.116]}
        scale={0.039}
      />
      <mesh
        geometry={nodes["Cube_-_copy_48"].geometry}
        material={materials.Material}
        position={[-0.066, -0.696, 0.727]}
        rotation={[-0.668, -0.615, -2.446]}
        scale={0.016}
      />
      <mesh
        geometry={nodes["Cube_-_copy_49"].geometry}
        material={materials.Material}
        position={[-0.854, -0.434, 0.308]}
        rotation={[2.913, 0.444, 1.237]}
        scale={0.015}
      />
      <mesh
        geometry={nodes["Cube_-_copy_50"].geometry}
        material={materials.Material}
        position={[-0.281, -0.149, 0.976]}
        rotation={[1.349, 1.174, 0.542]}
        scale={0.042}
      />
      <mesh
        geometry={nodes["Cube_-_copy_51"].geometry}
        material={materials.Material}
        position={[0.497, 0.717, 0.512]}
        rotation={[0.193, -0.832, -0.561]}
        scale={0.015}
      />
      <mesh
        geometry={nodes["Cube_-_copy_52"].geometry}
        material={materials.Material}
        position={[-0.049, 0.026, -1.02]}
        rotation={[1.475, -0.134, 2.815]}
        scale={0.033}
      />
      <mesh
        geometry={nodes["Cube_-_copy_53"].geometry}
        material={materials.Material}
        position={[-0.194, 0.139, 0.98]}
        rotation={[2.375, -1.294, 0.915]}
        scale={0.015}
      />
      <mesh
        geometry={nodes["Cube_-_copy_54"].geometry}
        material={materials.Material}
        position={[-0.556, -0.656, 0.559]}
        rotation={[-1.922, -0.715, 1.813]}
        scale={0.037}
      />
      <mesh
        geometry={nodes["Cube_-_copy_55"].geometry}
        material={materials.Material}
        position={[-0.356, -0.916, -0.219]}
        rotation={[-2.531, 0.718, 0.431]}
        scale={0.012}
      />
      <mesh
        geometry={nodes["Cube_-_copy_56"].geometry}
        material={materials.Material}
        position={[-0.554, 0.749, 0.378]}
        rotation={[-2.531, -0.471, 2.919]}
        scale={0.012}
      />
      <mesh
        geometry={nodes["Cube_-_copy_57"].geometry}
        material={materials.Material}
        position={[0.176, 0.228, -0.986]}
        rotation={[-1.414, 0.759, 0.324]}
        scale={0.038}
      />
      <mesh
        geometry={nodes["Cube_-_copy_58"].geometry}
        material={materials.Material}
        position={[0.647, 0.079, 0.763]}
        rotation={[0.625, -0.427, -1.08]}
        scale={0.015}
      />
      <mesh
        geometry={nodes["Cube_-_copy_59"].geometry}
        material={materials.Material}
        position={[-0.449, -0.788, 0.486]}
        rotation={[0.679, 1.101, 1.614]}
        scale={0.043}
      />
      <mesh
        geometry={nodes["Cube_-_copy_60"].geometry}
        material={materials.Material}
        position={[0.52, 0.865, -0.054]}
        rotation={[-2.177, -0.747, -2.458]}
        scale={0.018}
      />
      <mesh
        geometry={nodes["Cube_-_copy_61"].geometry}
        material={materials.Material}
        position={[0.957, 0.296, 0.127]}
        rotation={[3.08, -0.305, -2.139]}
        scale={0.022}
      />
      <mesh
        geometry={nodes["Cube_-_copy_62"].geometry}
        material={materials.Material}
        position={[-0.862, -0.534, 0.129]}
        rotation={[1.319, 0.231, 1.341]}
        scale={0.034}
      />
      <mesh
        geometry={nodes["Cube_-_copy_63"].geometry}
        material={materials.Material}
        position={[-0.725, 0.003, 0.729]}
        rotation={[2.889, -0.627, 1.402]}
        scale={0.034}
      />
      <mesh
        geometry={nodes["Cube_-_copy_64"].geometry}
        material={materials.Material}
        position={[0.346, 0.684, 0.675]}
        rotation={[2.619, 0.888, -1.674]}
        scale={0.034}
      />
      <mesh
        geometry={nodes["Cube_-_copy_65"].geometry}
        material={materials.Material}
        position={[0.716, -0.701, -0.234]}
        rotation={[-2.729, -0.003, -1.208]}
        scale={0.041}
      />
      <mesh
        geometry={nodes["Cube_-_copy_66"].geometry}
        material={materials.Material}
        position={[0.271, 0.935, -0.34]}
        rotation={[2.572, -0.275, -2.777]}
        scale={0.043}
      />
      <mesh
        geometry={nodes["Cube_-_copy_67"].geometry}
        material={materials.Material}
        position={[1.02, 0.077, -0.02]}
        rotation={[-1.955, -0.079, -1.216]}
        scale={0.035}
      />
      <mesh
        geometry={nodes["Cube_-_copy_68"].geometry}
        material={materials.Material}
        position={[0.85, 0.533, -0.19]}
        rotation={[0.711, 0.409, -1.751]}
        scale={0.031}
      />
      <mesh
        geometry={nodes["Cube_-_copy_69"].geometry}
        material={materials.Material}
        position={[-0.806, 0.466, -0.427]}
        rotation={[0.831, -0.508, 2.042]}
        scale={0.039}
      />
      <mesh
        geometry={nodes["Cube_-_copy_70"].geometry}
        material={materials.Material}
        position={[-0.549, 0.278, -0.828]}
        rotation={[-1.062, -0.623, 0.008]}
        scale={0.044}
      />
      <mesh
        geometry={nodes["Cube_-_copy_71"].geometry}
        material={materials.Material}
        position={[-0.602, -0.83, -0.1]}
        rotation={[-3.028, 0.69, 0.701]}
        scale={0.042}
      />
      <mesh
        geometry={nodes["Cube_-_copy_72"].geometry}
        material={materials.Material}
        position={[0.102, 0.763, 0.672]}
        rotation={[-2.19, 0.8, 2.662]}
        scale={0.033}
      />
      <mesh
        geometry={nodes["Cube_-_copy_73"].geometry}
        material={materials.Material}
        position={[-0.856, -0.528, 0.107]}
        rotation={[0.42, 0.78, 2.084]}
        scale={0.022}
      />
      <mesh
        geometry={nodes["Cube_-_copy_74"].geometry}
        material={materials.Material}
        position={[-0.068, -0.754, 0.671]}
        rotation={[-0.33, -0.906, -2.91]}
        scale={0.021}
      />
      <mesh
        geometry={nodes["Cube_-_copy_75"].geometry}
        material={materials.Material}
        position={[0.947, 0.151, -0.317]}
        rotation={[-2.471, 0.006, -1.969]}
        scale={0.021}
      />
      <mesh
        geometry={nodes["Cube_-_copy_76"].geometry}
        material={materials.Material}
        position={[-0.403, 0.915, -0.148]}
        rotation={[3.073, 0.583, 2.841]}
        scale={0.018}
      />
      <mesh
        geometry={nodes["Cube_-_copy_77"].geometry}
        material={materials.Material}
        position={[-0.483, 0.679, 0.568]}
        rotation={[-1.068, 1.056, 1.779]}
        scale={0.017}
      />
      <mesh
        geometry={nodes["Cube_-_copy_78"].geometry}
        material={materials.Material}
        position={[0.444, 0.705, 0.584]}
        rotation={[-0.599, -1.466, -1.094]}
        scale={0.026}
      />
      <mesh
        geometry={nodes["Cube_-_copy_79"].geometry}
        material={materials.Material}
        position={[0.828, 0.203, -0.57]}
        rotation={[-1.442, -0.238, -0.596]}
        scale={0.033}
      />
      <mesh
        geometry={nodes["Cube_-_copy_80"].geometry}
        material={materials.Material}
        position={[-0.115, 0.202, -0.991]}
        rotation={[-1.388, -0.796, 0.496]}
        scale={0.028}
      />
      <mesh
        geometry={nodes["Cube_-_copy_81"].geometry}
        material={materials.Material}
        position={[-0.742, -0.333, -0.599]}
        rotation={[0.65, -1.008, 2.497]}
        scale={0.023}
      />
      <mesh
        geometry={nodes["Cube_-_copy_82"].geometry}
        material={materials.Material}
        position={[0.676, 0.276, 0.712]}
        rotation={[-2.118, 0.681, -2.569]}
        scale={0.032}
      />
      <mesh
        geometry={nodes["Cube_-_copy_83"].geometry}
        material={materials.Material}
        position={[0.73, 0.003, -0.726]}
        rotation={[1.034, 0.058, -2.196]}
        scale={0.036}
      />
      <mesh
        geometry={nodes["Cube_-_copy_84"].geometry}
        material={materials.Material}
        position={[-0.283, -0.234, -0.955]}
        rotation={[1.013, -0.555, 2.405]}
        scale={0.036}
      />
      <mesh
        geometry={nodes["Cube_-_copy_85"].geometry}
        material={materials.Material}
        position={[-0.748, 0.398, 0.557]}
        rotation={[0.441, 1.109, 0.981]}
        scale={0.022}
      />
      <mesh
        geometry={nodes["Cube_-_copy_86"].geometry}
        material={materials.Material}
        position={[0.358, -0.939, 0.155]}
        rotation={[-2.049, 0.958, -1.197]}
        scale={0.021}
      />
      <mesh
        geometry={nodes["Cube_-_copy_87"].geometry}
        material={materials.Material}
        position={[-0.544, 0.78, -0.365]}
        rotation={[-0.761, -0.434, 0.057]}
        scale={0.028}
      />
      <mesh
        geometry={nodes["Cube_-_copy_88"].geometry}
        material={materials.Material}
        position={[-1.005, -0.001, -0.101]}
        rotation={[-0.912, -0.251, 1.181]}
        scale={0.018}
      />
      <mesh
        geometry={nodes["Cube_-_copy_89"].geometry}
        material={materials.Material}
        position={[0.002, 0.728, -0.724]}
        rotation={[-1.711, -1.313, -0.637]}
        scale={0.033}
      />
      <mesh
        geometry={nodes["Cube_-_copy_90"].geometry}
        material={materials.Material}
        position={[0.948, 0.335, 0.082]}
        rotation={[-2.653, -0.406, -1.826]}
        scale={0.02}
      />
      <mesh
        geometry={nodes["Cube_-_copy_91"].geometry}
        material={materials.Material}
        position={[-0.179, 0.934, -0.353]}
        rotation={[-2.803, 0.777, 2.139]}
        scale={0.019}
      />
    </group>
  );
}

useGLTF.preload("./assets/chocolate_chips.glb");
